### ISSUE TITLE
I reported an error in Xcode when building the plugin

### ISSUE THREAD

**Issue by RookieDeveloper-Wang** [MozillaReality/servo-unity#8]
![1604567870(1)](https://user-images.githubusercontent.com/30172230/98228317-6203c580-1f93-11eb-89d1-5434b71d1e82.png)

library not found for -lsimpleservo2

I can't find the file

Thanks in advance~

**Comment by philip-lamb** [comment]
Please feel free to repost this at https://github.com/philip-lamb/servo-unity

**Comment by chriisduran** [comment]
Hi, i would like to know, in Readme of Servo-Unity say that the plugin will be placed on ...Assets/Plugins

But the folder is empty
When i try to run it on Unity i have error of dll because the plugins folder is empty i think

Can you check that? or i have to build the plugin by myself?
Is a little confusing for me still build the plugin!
