### ISSUE TITLE
Can someone create a simple Alpha release of the `.unity`?

### ISSUE THREAD

**Issue by mikemilla** [MozillaReality/servo-unity#9]
I would love to try this out but am developing on windows. If someone could get a release of this that would be very helpful for people stopping by.

Totally understandable that this is early stuff, but this looks like one of the most promising web plugins at the moment.

**Comment by philip-lamb** [comment]
Windows is not yet supported. Some preliminary work has been done on Windows support, but this is not yet complete. 

Since Mozilla Research was closed by Mozilla in September 2020, I and the rest of the Servo team are no longer with Mozilla. The Servo project is now under the stewardship of the Linux Foundation. All future work on Servo Unity will take place in my repo at https://github.com/philip-lamb/servo-unity.

**Comment by mikemilla** [comment]
Thank you for the update and your hardwork @philip-lamb <3

**Comment by veqtor** [comment]
Do you think you'll be able to complete windows support anytime soon?
